
logging:
  level:
    com.pedrol129: DEBUG

spring:
  main:
    banner-mode: "off"
        
title: ' 
   _   _ _____  ______ _____ _      _____  ______ _       _____   __  _____   ___  ___  ___ _____ 
  | \ | |  _  | | ___ \  _  | |    |  ___| | ___ \ |     / _ \ \ / / |  __ \ / _ \ |  \/  ||  ___|
  |  \| | | | | | |_/ / | | | |    | |__   | |_/ / |    / /_\ \ V /  | |  \// /_\ \| .  . || |__  
  | . ` | | | | |    /| | | | |    |  __|  |  __/| |    |  _  |\ /   | | __ |  _  || |\/| ||  __| 
  | |\  \ \_/ / | |\ \\ \_/ / |____| |___  | |   | |____| | | || |   | |_\ \| | | || |  | || |___ 
  \_| \_/\___/  \_| \_|\___/\_____/\____/  \_|   \_____/\_| |_/\_/    \____/\_| |_/\_|  |_/\____/ 
  '    