graph TD
    A[Found Items] --> |For each| Item
    Item --> FreePositions{Have free positions}
    FreePositions --> |Yes| Equip
    FreePositions --> |No| Type{Type}
    Type --> |Weapon| E{Powerfull than the weak item}
    E --> |Yes| Equip
    E --> |No| Inventory{Best combination  with inventory items}
    Inventory --> |No| End
    Inventory --> |Yes| Equip
    Type --> |Armor| E
    Type --> |Shield| B{Powerfull than the weak item}
    B --> |Yes| H{Have other weapon}
    H --> |No| Inventory
    H --> note[[Example: Found a shield, but you only have a two-hand weapon]]
    H --> |Yes| Equip